# Generated by Django 4.2.3 on 2023-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=80, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.PositiveIntegerField(null=True, verbose_name='Product price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_hy',
            field=models.PositiveIntegerField(null=True, verbose_name='Product price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ru',
            field=models.PositiveIntegerField(null=True, verbose_name='Product price'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='SubCategory name'),
        ),
    ]
