# Generated by Django 4.2.3 on 2023-07-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_name_en_category_name_hy_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ru',
        ),
    ]
